//! Data lineage tracking for versioned data.
//!
//! This module provides comprehensive data lineage tracking capabilities,
//! allowing users to trace the origin, transformations, and dependencies
//! of data across versions in a distributed multi-agent system.
//!
//! # Key Concepts
//!
//! - **Lineage**: The complete record of a data item's origin, transformations,
//!   and movement through the system.
//! - **Provenance**: Information about the sources and processes that produced
//!   a particular data item.
//! - **Dependency Graph**: A graph structure showing relationships between
//!   different data versions and transformations.
//! - **Transformation**: An operation that transforms data from one state to another.

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use uuid::Uuid;

/// Represents the origin of a data item.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DataOrigin {
    /// Data was created by a sensor or external source.
    Sensor {
        sensor_id: String,
        timestamp: u64,
        location: Option<String>,
    },
    /// Data was generated by an agent.
    Agent {
        agent_id: crate::common::types::AgentId,
        timestamp: u64,
        operation: String,
    },
    /// Data was imported from an external system.
    ExternalSystem {
        system_name: String,
        import_id: String,
        timestamp: u64,
    },
    /// Data was synthesized or generated algorithmically.
    Synthetic {
        generator: String,
        parameters: HashMap<String, String>,
        timestamp: u64,
    },
    /// Unknown origin.
    Unknown,
}

/// A transformation applied to data.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Transformation {
    /// Unique identifier for this transformation.
    pub id: Uuid,
    /// Type of transformation.
    pub transformation_type: TransformationType,
    /// Parameters used in the transformation.
    pub parameters: HashMap<String, String>,
    /// Agent that performed the transformation.
    pub agent_id: Option<crate::common::types::AgentId>,
    /// Timestamp when transformation occurred.
    pub timestamp: u64,
    /// Input data versions.
    pub inputs: Vec<DataReference>,
    /// Output data versions.
    pub outputs: Vec<DataReference>,
    /// Metadata about the transformation.
    pub metadata: HashMap<String, String>,
}

/// Type of data transformation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TransformationType {
    /// Filter operation (e.g., remove outliers).
    Filter,
    /// Aggregation (e.g., sum, average).
    Aggregate,
    /// Join operation combining multiple datasets.
    Join,
    /// Transformation (e.g., normalization, encoding).
    Transform,
    /// Machine learning model inference.
    Inference,
    /// Data cleaning operation.
    Clean,
    /// Anonymization or privacy transformation.
    Anonymize,
    /// Custom transformation.
    Custom(String),
}

/// Reference to a specific version of data.
#[derive(Debug, Clone, Serialize, Deserialize, Hash, Eq, PartialEq)]
pub struct DataReference {
    /// Data identifier (e.g., dataset name, key).
    pub data_id: String,
    /// Version of the data.
    pub version: crate::version::Version,
    /// Optional location/URI of the data.
    pub location: Option<String>,
}

/// Complete lineage information for a data item.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataLineage {
    /// Unique identifier for this lineage record.
    pub id: Uuid,
    /// Reference to the data item.
    pub data_ref: DataReference,
    /// Origin of the data.
    pub origin: DataOrigin,
    /// Chain of transformations that produced this data.
    pub transformation_chain: Vec<Arc<Transformation>>,
    /// Direct dependencies (parent data items).
    pub dependencies: Vec<DataReference>,
    /// Data items that depend on this one.
    pub dependents: Vec<DataReference>,
    /// Quality metrics associated with this data.
    pub quality_metrics: HashMap<String, f64>,
    /// Compliance and governance information.
    pub compliance: ComplianceInfo,
    /// Timestamp when lineage was recorded.
    pub recorded_at: u64,
}

/// Compliance and governance information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceInfo {
    /// Data classification (e.g., public, confidential, restricted).
    pub classification: String,
    /// Retention policy in seconds (None = indefinite).
    pub retention_period: Option<u64>,
    /// Geographic restrictions.
    pub geographic_restrictions: Vec<String>,
    /// Privacy regulations compliance (GDPR, CCPA, etc.).
    pub privacy_compliance: Vec<String>,
    /// Whether lineage tracking is required for compliance.
    pub lineage_required: bool,
}

/// Builder for constructing data lineage records.
pub struct LineageBuilder {
    data_ref: DataReference,
    origin: DataOrigin,
    transformations: Vec<Arc<Transformation>>,
    dependencies: Vec<DataReference>,
    quality_metrics: HashMap<String, f64>,
    compliance: ComplianceInfo,
}

impl LineageBuilder {
    /// Create a new lineage builder.
    pub fn new(data_ref: DataReference, origin: DataOrigin) -> Self {
        Self {
            data_ref,
            origin,
            transformations: Vec::new(),
            dependencies: Vec::new(),
            quality_metrics: HashMap::new(),
            compliance: ComplianceInfo {
                classification: "unclassified".to_string(),
                retention_period: None,
                geographic_restrictions: Vec::new(),
                privacy_compliance: Vec::new(),
                lineage_required: false,
            },
        }
    }

    /// Add a transformation to the lineage.
    pub fn add_transformation(mut self, transformation: Transformation) -> Self {
        self.transformations.push(Arc::new(transformation));
        self
    }

    /// Add a dependency to the lineage.
    pub fn add_dependency(mut self, dependency: DataReference) -> Self {
        self.dependencies.push(dependency);
        self
    }

    /// Add multiple dependencies.
    pub fn add_dependencies(mut self, dependencies: Vec<DataReference>) -> Self {
        self.dependencies.extend(dependencies);
        self
    }

    /// Add a quality metric.
    pub fn add_quality_metric(mut self, metric_name: String, value: f64) -> Self {
        self.quality_metrics.insert(metric_name, value);
        self
    }

    /// Set compliance information.
    pub fn with_compliance(mut self, compliance: ComplianceInfo) -> Self {
        self.compliance = compliance;
        self
    }

    /// Build the final data lineage record.
    pub fn build(self) -> DataLineage {
        DataLineage {
            id: Uuid::new_v4(),
            data_ref: self.data_ref,
            origin: self.origin,
            transformation_chain: self.transformations,
            dependencies: self.dependencies,
            dependents: Vec::new(), // Will be populated by LineageTracker
            quality_metrics: self.quality_metrics,
            compliance: self.compliance,
            recorded_at: std::time::SystemTime::now()
                .duration_since(std::time::SystemTime::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs(),
        }
    }
}

/// Tracks lineage relationships across the system.
pub struct LineageTracker {
    /// Map from data reference to its lineage.
    lineage_map: HashMap<DataReference, DataLineage>,
    /// Map from transformation ID to transformation.
    transformation_map: HashMap<Uuid, Arc<Transformation>>,
    /// Dependency graph for querying relationships.
    dependency_graph: DependencyGraph,
}

impl LineageTracker {
    /// Create a new lineage tracker.
    pub fn new() -> Self {
        Self {
            lineage_map: HashMap::new(),
            transformation_map: HashMap::new(),
            dependency_graph: DependencyGraph::new(),
        }
    }

    /// Register a data lineage record.
    pub fn register_lineage(&mut self, lineage: DataLineage) -> Result<(), LineageError> {
        // Check if lineage already exists
        if self.lineage_map.contains_key(&lineage.data_ref) {
            return Err(LineageError::DuplicateLineage(lineage.data_ref.data_id.clone()));
        }

        // Register all transformations
        for transformation in &lineage.transformation_chain {
            self.transformation_map.insert(transformation.id, transformation.clone());
        }

        // Update dependency graph
        for dependency in &lineage.dependencies {
            self.dependency_graph.add_dependency(dependency.clone(), lineage.data_ref.clone());
        }

        // Store lineage
        self.lineage_map.insert(lineage.data_ref.clone(), lineage);

        Ok(())
    }

    /// Get lineage for a specific data reference.
    pub fn get_lineage(&self, data_ref: &DataReference) -> Option<&DataLineage> {
        self.lineage_map.get(data_ref)
    }

    /// Find all data items that depend on the given data.
    pub fn find_dependents(&self, data_ref: &DataReference) -> Vec<&DataReference> {
        self.dependency_graph.get_dependents(data_ref)
    }

    /// Find the provenance (origin and transformation chain) for data.
    pub fn get_provenance(&self, data_ref: &DataReference) -> Option<ProvenanceResult> {
        let lineage = self.lineage_map.get(data_ref)?;
        
        let mut transformation_chain = Vec::new();
        let mut visited = HashSet::new();
        
        self.collect_provenance_chain(&lineage.transformation_chain, &mut transformation_chain, &mut visited);
        
        Some(ProvenanceResult {
            origin: lineage.origin.clone(),
            transformation_chain,
            total_transformations: visited.len(),
        })
    }

    /// Recursively collect the complete provenance chain.
    fn collect_provenance_chain(
        &self,
        transformations: &[Arc<Transformation>],
        result: &mut Vec<Arc<Transformation>>,
        visited: &mut HashSet<Uuid>,
    ) {
        for transformation in transformations {
            if visited.insert(transformation.id) {
                result.push(transformation.clone());
                
                // Recursively process input transformations
                for input in &transformation.inputs {
                    if let Some(lineage) = self.lineage_map.get(input) {
                        self.collect_provenance_chain(&lineage.transformation_chain, result, visited);
                    }
                }
            }
        }
    }

    /// Query lineage by various criteria.
    pub fn query_lineage(&self, query: LineageQuery) -> Vec<&DataLineage> {
        self.lineage_map.values()
            .filter(|lineage| query.matches(lineage))
            .collect()
    }

    /// Export lineage data for audit or analysis.
    pub fn export_lineage(&self, format: ExportFormat) -> Result<String, LineageError> {
        match format {
            ExportFormat::Json => {
                let lineages: Vec<&DataLineage> = self.lineage_map.values().collect();
                serde_json::to_string_pretty(&lineages)
                    .map_err(|e| LineageError::SerializationError(e.to_string()))
            }
            ExportFormat::Graphviz => {
                Ok(self.dependency_graph.to_graphviz())
            }
        }
    }

    /// Import lineage data from external source.
    pub fn import_lineage(&mut self, data: &str, format: ExportFormat) -> Result<(), LineageError> {
        match format {
            ExportFormat::Json => {
                let lineages: Vec<DataLineage> = serde_json::from_str(data)
                    .map_err(|e| LineageError::DeserializationError(e.to_string()))?;
                
                for lineage in lineages {
                    self.register_lineage(lineage)?;
                }
                
                Ok(())
            }
            ExportFormat::Graphviz => {
                Err(LineageError::UnsupportedFormat("Graphviz import not implemented".to_string()))
            }
        }
    }
}

/// Graph structure for tracking dependencies.
struct DependencyGraph {
    /// Map from data to its direct dependents.
    dependents: HashMap<DataReference, Vec<DataReference>>,
    /// Map from data to its dependencies.
    dependencies: HashMap<DataReference, Vec<DataReference>>,
}

impl DependencyGraph {
    fn new() -> Self {
        Self {
            dependents: HashMap::new(),
            dependencies: HashMap::new(),
        }
    }

    fn add_dependency(&mut self, dependency: DataReference, dependent: DataReference) {
        // Add to dependents map
        self.dependents.entry(dependency.clone())
            .or_insert_with(Vec::new)
            .push(dependent.clone());
        
        // Add to dependencies map
        self.dependencies.entry(dependent)
            .or_insert_with(Vec::new)
            .push(dependency);
    }

    fn get_dependents(&self, data_ref: &DataReference) -> Vec<&DataReference> {
        self.dependents.get(data_ref)
            .map(|deps| deps.iter().collect())
            .unwrap_or_else(Vec::new)
    }

    fn get_dependencies(&self, data_ref: &DataReference) -> Vec<&DataReference> {
        self.dependencies.get(data_ref)
            .map(|deps| deps.iter().collect())
            .unwrap_or_else(Vec::new)
    }

    fn to_graphviz(&self) -> String {
        let mut output = String::new();
        output.push_str("digraph Lineage {\n");
        output.push_str("  rankdir=LR;\n");
        output.push_str("  node [shape=box];\n\n");
        
        // Add nodes
        for (data_ref, _) in &self.dependencies {
            let label = format!("{}\\n{}", data_ref.data_id, data_ref.version.to_string());
            output.push_str(&format!("  \"{}\" [label=\"{}\"];\n", 
                data_ref.data_id, label));
        }
        
        // Add edges
        for (dependent, dependencies) in &self.dependencies {
            for dependency in dependencies {
                output.push_str(&format!("  \"{}\" -> \"{}\";\n", 
                    dependency.data_id, dependent.data_id));
            }
        }
        
        output.push_str("}\n");
        output
    }
}

/// Query for filtering lineage records.
#[derive(Debug, Clone)]
pub struct LineageQuery {
    /// Filter by data ID pattern.
    pub data_id_pattern: Option<String>,
    /// Filter by agent ID.
    pub agent_id: Option<crate::common::types::AgentId>,
    /// Filter by time range.
    pub time_range: Option<(u64, u64)>,
    /// Filter by transformation type.
    pub transformation_type: Option<TransformationType>,
    /// Filter by compliance classification.
    pub classification: Option<String>,
    /// Maximum depth of transformation chain.
    pub max_depth: Option<usize>,
}

impl LineageQuery {
    /// Check if a lineage record matches the query.
    pub fn matches(&self, lineage: &DataLineage) -> bool {
        // Check data ID pattern
        if let Some(pattern) = &self.data_id_pattern {
            if !lineage.data_ref.data_id.contains(pattern) {
                return false;
            }
        }
        
        // Check time range
        if let Some((start, end)) = self.time_range {
            if lineage.recorded_at < start || lineage.recorded_at > end {
                return false;
            }
        }
        
        // Check classification
        if let Some(classification) = &self.classification {
            if &lineage.compliance.classification != classification {
                return false;
            }
        }
        
        // Check transformation type
        if let Some(transformation_type) = &self.transformation_type {
            let has_matching_transformation = lineage.transformation_chain.iter()
                .any(|t| match (&t.transformation_type, transformation_type) {
                    (TransformationType::Custom(a), TransformationType::Custom(b)) => a == b,
                    (a, b) => std::mem::discriminant(a) == std::mem::discriminant(b),
                });
            
            if !has_matching_transformation {
                return false;
            }
        }
        
        // Check max depth
        if let Some(max_depth) = self.max_depth {
            if lineage.transformation_chain.len() > max_depth {
                return false;
            }
        }
        
        true
    }
}

/// Result of a provenance query.
#[derive(Debug, Clone)]
pub struct ProvenanceResult {
    /// Origin of the data.
    pub origin: DataOrigin,
    /// Complete chain of transformations.
    pub transformation_chain: Vec<Arc<Transformation>>,
    /// Total number of unique transformations.
    pub total_transformations: usize,
}

/// Format for exporting lineage data.
#[derive(Debug, Clone)]
pub enum ExportFormat {
    /// JSON format for interoperability.
    Json,
    /// Graphviz format for visualization.
    Graphviz,
}

/// Errors that can occur in lineage tracking.
#[derive(Debug, thiserror::Error)]
pub enum LineageError {
    #[error("Duplicate lineage for data ID: {0}")]
    DuplicateLineage(String),
    
    #[error("Serialization error: {0}")]
    SerializationError(String),
    
    #[error("Deserialization error: {0}")]
    DeserializationError(String),
    
    #[error("Unsupported format: {0}")]
    UnsupportedFormat(String),
    
    #[error("Lineage not found for data reference")]
    LineageNotFound,
    
    #[error("Invalid data reference: {0}")]
    InvalidDataReference(String),
}

/// Integration with the existing version manager.
pub mod integration {
    use super::*;
    use crate::manager::VersionManager;
    
    /// Extended version manager with lineage tracking.
    pub struct VersionManagerWithLineage {
        version_manager: VersionManager,
        lineage_tracker: LineageTracker,
    }
    
    impl VersionManagerWithLineage {
        /// Create a new version manager with lineage tracking.
        pub fn new(version_manager: VersionManager) -> Self {
            Self {
                version_manager,
                lineage_tracker: LineageTracker::new(),
            }
        }
        
        /// Create a snapshot with lineage information.
        pub async fn create_snapshot_with_lineage(
            &mut self,
            data_id: String,
            description: String,
            origin: DataOrigin,
            transformations: Vec<Transformation>,
            dependencies: Vec<DataReference>,
        ) -> Result<(crate::version::Snapshot, DataLineage), crate::error::Error> {
            // Create snapshot using existing manager
            let snapshot = self.version_manager.create_snapshot(&data_id, description).await?;
            
            // Build data reference
            let data_ref = DataReference {
                data_id: data_id.clone(),
                version: snapshot.version.clone(),
                location: None,
            };
            
            // Build lineage
            let lineage_builder = LineageBuilder::new(data_ref.clone(), origin);
            
            let lineage = lineage_builder
                .add_dependencies(dependencies)
                .build();
            
            // Register lineage
            self.lineage_tracker.register_lineage(lineage.clone())
                .map_err(|e| crate::error::Error::LineageError(e.to_string()))?;
            
            Ok((snapshot, lineage))
        }
        
        /// Get lineage for a snapshot.
        pub fn get_snapshot_lineage(
            &self,
            snapshot: &crate::version::Snapshot,
        ) -> Option<&DataLineage> {
            let data_ref = DataReference {
                data_id: snapshot.metadata.get("data_id").cloned().unwrap_or_default(),
                version: snapshot.version.clone(),
                location: None,
            };
            
            self.lineage_tracker.get_lineage(&data_ref)
        }
        
        /// Get the underlying lineage tracker.
        pub fn lineage_tracker(&self) -> &LineageTracker {
            &self.lineage_tracker
        }
        
        /// Get mutable access to the lineage tracker.
        pub fn lineage_tracker_mut(&mut self) -> &mut LineageTracker {
            &mut self.lineage_tracker
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::version::Version;
    use crate::common::types::AgentId;
    
    fn sample_agent_id() -> AgentId {
        AgentId::from_u128(12345)
    }
    
    fn sample_version() -> Version {
        Version::new(1, sample_agent_id())
    }
    
    fn sample_data_reference() -> DataReference {
        DataReference {
            data_id: "test_dataset".to_string(),
            version: sample_version(),
            location: Some("memory://test".to_string()),
        }
    }
    
    #[test]
    fn test_lineage_builder() {
        let data_ref = sample_data_reference();
        let origin = DataOrigin::Agent {
            agent_id: sample_agent_id(),
            timestamp: 1000,
            operation: "create".to_string(),
        };
        
        let lineage = LineageBuilder::new(data_ref.clone(), origin)
            .add_quality_metric("accuracy".to_string(), 0.95)
            .build();
        
        assert_eq!(lineage.data_ref.data_id, "test_dataset");
        assert_eq!(lineage.quality_metrics.get("accuracy"), Some(&0.95));
    }
    
    #[test]
    fn test_lineage_tracker() {
        let mut tracker = LineageTracker::new();
        
        let data_ref = sample_data_reference();
        let origin = DataOrigin::Agent {
            agent_id: sample_agent_id(),
            timestamp: 1000,
            operation: "create".to_string(),
        };
        
        let lineage = LineageBuilder::new(data_ref.clone(), origin).build();
        
        assert!(tracker.register_lineage(lineage.clone()).is_ok());
        assert!(tracker.get_lineage(&data_ref).is_some());
        
        // Test duplicate registration
        assert!(tracker.register_lineage(lineage).is_err());
    }
    
    #[test]
    fn test_dependency_graph() {
        let mut graph = DependencyGraph::new();
        
        let dep1 = DataReference {
            data_id: "source1".to_string(),
            version: sample_version(),
            location: None,
        };
        
        let dep2 = DataReference {
            data_id: "source2".to_string(),
            version: sample_version(),
            location: None,
        };
        
        let dependent = DataReference {
            data_id: "result".to_string(),
            version: sample_version(),
            location: None,
        };
        
        graph.add_dependency(dep1.clone(), dependent.clone());
        graph.add_dependency(dep2.clone(), dependent.clone());
        
        let dependents = graph.get_dependents(&dep1);
        assert_eq!(dependents.len(), 1);
        assert_eq!(dependents[0].data_id, "result");
    }
}